warmupIterations: 10
benchmarkIterations: 10
shrinkBatchSources: 30
batchSamples: 10
individualBatchSources: false
variants:   
#  - standard
  - recovery
  - recoveryInlined
languages:
  - id: java
    name: Java
    extension: java
    parseTable:
      repo: https://github.com/metaborg/java-front.git
      subDir: lang.java
    sources:
      batch:
        - id: apache-commons-lang
          repo: https://github.com/apache/commons-lang.git
        - id: netty
          repo: https://github.com/netty/netty.git
        - id: spring-boot
          repo: https://github.com/spring-projects/spring-boot.git
          branch: main
#      incremental:
#        - id: apache-commons-lang-incremental
#          repo: https://github.com/apache/commons-lang.git
#          fetchOptions:
#            - '--depth=200'
#        - id: apache-commons-lang-stringutils
#          repo: https://github.com/apache/commons-lang.git
#          files:
#            - src/main/java/org/apache/commons/lang3/StringUtils.java
    antlrBenchmarks:
      - id: antlr
        benchmark: ANTLRJava8Benchmark
      - id: antlr-optimized
        benchmark: ANTLRJavaBenchmark
  - id: webdsl
    name: WebDSL
    extension: app
    parseTable:
      repo: https://github.com/webdsl/webdsl-statix.git
      subDir: webdslstatix
    sources:
      batch:
        - id: webdsl-yellowgrass
          repo: https://github.com/webdsl/yellowgrass
        - id: webdsl-elib-example
          repo: https://github.com/webdsl/elib-example
        - id: webdsl-elib-ace
          repo: https://github.com/webdsl/elib-ace
        - id: webdsl-elib-tablesorter
          repo: https://github.com/webdsl/elib-tablesorter
        - id: webdsl-elib-utils
          repo: https://github.com/webdsl/elib-utils
        - id: webdsl-elib-bootstrap
          repo: https://github.com/webdsl/elib-bootstrap
        - id: webdsl-elib-unsavedchanges
          repo: https://github.com/webdsl/elib-unsavedchanges
        - id: webdsl-elib-timeline
          repo: https://github.com/webdsl/elib-timeline
        - id: webdsl-elib-timezones
          repo: https://github.com/webdsl/elib-timezones
        - id: webdsl-elib-holder
          repo: https://github.com/webdsl/elib-holder
#      incremental:
#        - id: webdsl-yellowgrass-incremental
#          repo: https://github.com/webdsl/yellowgrass
#          fetchOptions:
#            - '--depth=200'
#        - id: webdsl-builtin
#          repo: https://github.com/webdsl/webdsl
#          fetchOptions:
#            - '--shallow-since="2011-02-16 14:00:00 +0000"' # From this point in time on, the file parses without errors
#          files:
#            - src/org/webdsl/dsl/project/template-webdsl/built-in.app
  - id: sdf3
    name: SDF3
    extension: sdf3
    parseTable:
      repo: https://github.com/metaborg/sdf.git
      subDir: org.metaborg.meta.lang.template
    sources:
      batch:
        - id: nabl
          repo: https://github.com/metaborg/nabl
        - id: dynsem
          repo: https://github.com/metaborg/dynsem
        - id: flowspec
          repo: https://github.com/metaborg/flowspec
#  - id: ocaml
#    name: OCaml
#    extension: ml
#    parseTable:
#      repo: https://github.com/MetaBorgCube/metaborg-ocaml.git
#      subDir: ocaml
#      dynamic: true
#    sources:
#      batch:
#        - id: facebook-flow
#          repo: https://github.com/facebook/flow.git
